# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoCrazyRxMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoCrazyRxMVVM
pod 'RxSwift', '6.9.0'
pod 'RxCocoa', '6.9.0'

  target 'CryptoCrazyRxMVVMTests' do
    inherit! :search_paths
    # Pods for testing
pod 'RxBlocking', '6.9.0'
pod 'RxTest', '6.9.0'
  end

  target 'CryptoCrazyRxMVVMUITests' do
    # Pods for testing
  end

end
